name 'rharrison-lokkit'
version '0.5.0'

author 'Russell Harrison'
license 'GPLv3+'
project_page 'https://github.com/rharrison10/puppet-lokkit'
source 'https://github.com/rharrison10/puppet-lokkit'
summary 'Use lokkit to manage the iptables firewall.  More convenient than working with iptables directly.'
description 'Manage iptables with lokkit.  This module uses the lokkit command line tool to allow access to ports and services   You can also supply a set of custom iptables rules in a file using the lokkit::custom defined type.'
dependency 'puppetlabs/stdlib', '>=2.2.0'
